### ISSUE TITLE
view in <For ... is outdated for Leptos 0.5 - should be replaced with children

### ISSUE THREAD

**Issue by obioma** [Synphonyte/leptos-multi-drag#1]
src/multi_draggable/mod.rs  in lines 148 and 177 the 'view' expression should be exchanged with 'children' as part of the <For
Kindly refer to the current version documentation:  https://docs.rs/leptos/latest/leptos/fn.For.html
Thx

**Comment by maccesch** [comment]
Thanks for pointing this out. Fixing now...

**Comment by maccesch** [comment]
Fixed in b3890aa
